openapi: 3.0.3
info:
  title: Chat Craft API
  version: 1.0.0
paths:
  /api/generate:
    post:
      summary: Generate code
      tags:
        - CodeGeneration
      operationId: generateCode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppDesignRequest'
      responses:
        '200':
          description: Generated code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneratedCodeResponse'
components:
  schemas:
    AppDesignRequest:
      type: object
      properties:
        appName:
          type: string
          example: "MyApp"
        description:
          type: string
          example: "This is a sample app description."
      required:
        - appName
        - description

    GeneratedCodeResponse:
      type: object
      properties:
        generatedCode:
          type: string
          example: "Generated code content here."
        message:
          type: string
          example: "Code generated successfully"
        timestamp:
          type: string
          format: date-time
          example: "2024-06-30T08:30:00Z"
      required:
        - generatedCode
        - message
        - timestamp
