version: '3.8'

services:
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped

  backend-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-service
    ports:
      - "8080:8080"
    depends_on:
      - appsmith
    environment:
      APPSMITH_API_URL: http://appsmith:80
    restart: unless-stopped

  frontend-service:
    build:
      context: ./frontend
      dockerfile: Dockerfile.ui
    container_name: frontend-service
    ports:
      - "3000:80"
    depends_on:
      - backend-service
    restart: unless-stopped
