services:
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped

  chat-craft-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chat-craft-service
    ports:
      - "8080:8080"
    depends_on:
      - appsmith
    environment:
      APPSMITH_API_URL: http://appsmith:80
    restart: unless-stopped

  chat-craft-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.ui
    container_name: chat-craft-app
    ports:
      - "3000:4000"
    depends_on:
      - chat-craft-service
    restart: unless-stopped